version: '3'

services:
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER:-spaceman}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-spaceman}
      POSTGRES_DB: memecoinsniper

volumes:
  postgres-data:
