version: '3'

services:
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER:-spaceman}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-spaceman}
      POSTGRES_DB: memecoinsniper

  bot:
    image: danilavoronkov/memecoin-sniper
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
    env_file: ./.env
volumes:
  postgres-data:
